### ISSUE TITLE
iOS app crashes when setting progress to 0

### ISSUE THREAD

**Issue by ghost** [chen-fishbein/CN1CircleProgress#1]
Hi,

@shannah : As discussed on stackoverflow:

the CN1 app using CircleProgress will crash, when using setProgress with the value "0".
So:
```
CircleProgress cp = new CircleProgress();
cp.setProgress( 0 );
```
is causing the app to crash.

Best regards

**Comment by shannah** [comment]
This should be fixed for next server update.

**Comment by bengalischerHase** [comment]
Thanks for fixing this. As only setting the progress when it's larger than 0 does not work around this issue. It crashes in any case if the progress is only 0. So it cannot be displayed with progress 0 until the fix is available.

**Comment by ghost** [comment]
Thanks for fixing this. As only setting the progress when it's larger than 0 does not work around this issue. It crashes in any case if the progress is only 0. So it cannot be displayed with progress 0 until the fix is available.

**Comment by ghost** [comment]
I don't know if this commit or this (https://github.com/codenameone/CodenameOne/commit/82373114b62fe02fb403f11236770b140521295d) did the trick.
However it works now.
Only thing I wanted to mention is, that now there is a difference between:

- not setting progress if 0: does not show an arc at all
- setting the progress 0: shows a nice arc with no progress

Thanks again @shannah
